import axios from 'axios'
import Head from 'next/head'
import Posts from '../components/Posts/Posts'
import Sidebar from '../components/Sidebar/Sidebar'
export default function Home({posts}) {

  const postsArray = [];
  for(var i in posts) {
    postsArray.push([i,posts[i]]);
}

  return (
    <div>
      <Head>
        
        <title>Broadcast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.1/dist/flowbite.min.css" />
        {/* <script  type="module" src="../path/to/flowbite/dist/flowbite.js"></script> */}
      </Head>

      <main>
        <div className='flex justify-center bg-gray-100 py-4 px-24'>
          <div className='flex' >
            <Posts posts={postsArray} type='all' />
          </div>
          <div className='flex'>
            <Sidebar />
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  
  const response = await fetch('http://localhost:8080/api/posts')
  const posts = await response.json()
  
  return {
   props: {
    posts: posts
  }
  }
}
